# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 1
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/padraic/ee6621/fpga/labs/ct1/work_vivado_35t/ct1.cache/wt [current_project]
set_property parent.project_path /home/padraic/ee6621/fpga/labs/ct1/work_vivado_35t/ct1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /home/padraic/ee6621/fpga/labs/ct1/work_vivado_35t/ct1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
set_property include_dirs /home/padraic/ee6621/fpga/labs/ct1/includes [current_fileset]
read_verilog -library xil_defaultlib {
  /home/padraic/ee6621/fpga/labs/ct1/rtl/bcd_counter_4d.v
  /home/padraic/ee6621/fpga/labs/ct1/rtl/bcd_counter_digit.v
  /home/padraic/ee6621/fpga/labs/ct1/rtl/buzzer.v
  /home/padraic/ee6621/fpga/labs/ct1/rtl/clkgen_cmod_a7.v
  /home/padraic/ee6621/fpga/labs/ct1/rtl/counter_down_rld.v
  /home/padraic/ee6621/fpga/labs/ct1/rtl/ct1.v
  /home/padraic/ee6621/fpga/labs/ct1/rtl/debounce.v
  /home/padraic/ee6621/fpga/labs/ct1/rtl/display_7s.v
  /home/padraic/ee6621/fpga/labs/ct1/rtl/display_7s_mux.v
  /home/padraic/ee6621/fpga/labs/ct1/rtl/fsm_game.v
  /home/padraic/ee6621/fpga/labs/ct1/rtl/synchroniser_3s.v
  /home/padraic/ee6621/fpga/labs/ct1/rtl/fpga_wrapper_ct1.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/padraic/ee6621/fpga/labs/ct1/xdc/cmod-a7-config.xdc
set_property used_in_implementation false [get_files /home/padraic/ee6621/fpga/labs/ct1/xdc/cmod-a7-config.xdc]

read_xdc /home/padraic/ee6621/fpga/labs/ct1/xdc/rt2.xdc
set_property used_in_implementation false [get_files /home/padraic/ee6621/fpga/labs/ct1/xdc/rt2.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top fpga_wrapper_ct1 -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef fpga_wrapper_ct1.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file fpga_wrapper_ct1_utilization_synth.rpt -pb fpga_wrapper_ct1_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
